name: procon-gardener

on:
  schedule:
    - cron: "0 0 * * 3" # execute every Wednesday
  workflow_dispatch:

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install procon-gardener
      run: |
        go install github.com/togatoga/procon-gardener@latest
        procon-gardener init

    - name: Edit config.json
      run: |
        CONFIG_PATH="../../../.procon-gardener/config.json"
        jq '.atcoder.repository_path|="."' $CONFIG_PATH > tmp && mv tmp $CONFIG_PATH
        jq ".atcoder.user_id|=\"${{ secrets.ID_KEY }}\"" $CONFIG_PATH > tmp && mv tmp $CONFIG_PATH
        jq ".atcoder.user_email|=\"${{ secrets.EM_KEY }}\"" $CONFIG_PATH > tmp && mv tmp $CONFIG_PATH

    - name: Archive
      run: procon-gardener archive

    - name: Git push
      run: git push
